base: 'http://cms25.s2410456015.student.kwmhgb.at/'
dependencies:
  - fhooe/kwm2025
languages:
  -
    title: German
    enabled: true
    languageId: 0
    base: /
    locale: de_DE
    navigationTitle: Deutsch
    flag: at
    hreflang: de_DE
    websiteTitle: ''
  -
    title: English
    enabled: true
    locale: en_US
    hreflang: ''
    base: /en/
    websiteTitle: ''
    navigationTitle: English
    fallbackType: strict
    fallbacks: ''
    flag: en-us-gb
    languageId: 1
rootPageId: 1
websiteTitle: 'KWM 25'


routeEnhancers:
News:
  type: Extbase
  extension: News
  plugin: Pi1
  routes:
    - routePath: '/'
      _controller: 'News::list'
    - routePath: '/page-{page}'
      _controller: 'News::list'
      _arguments:
        page: 'currentPage'
    - routePath: '/{news-title}'
      _controller: 'News::detail'
      _arguments:
        news-title: news
  defaultController: 'News::list'
  defaults:
    page: '1'
  aspects:
    news:
      type: PersistedAliasMapper
      tableName: tx_news_domain_model_news
      routeFieldName: path_segment
    page:
      type: StaticRangeMapper
      start: '1'
      end: '100'
